
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author phkno
 */
public class App extends javax.swing.JFrame {
    
    private Restaurant restaurant;
    private Client client;
    private DefaultListModel orderItems = new DefaultListModel<>();
    private DefaultListModel activeOrders = new DefaultListModel<>();
    private DefaultListModel itemsSelectedOrder = new DefaultListModel<>();
    private DefaultListModel readyOrders = new DefaultListModel<>();

    /**
     * Creates new form App
     */
    public App() {
        this.restaurant = new Restaurant("Dog Mania");
        initComponents();
        this.client = new Client();
        this.itensOrderList.setModel(orderItems);
        this.activeOrdersList.setModel(activeOrders);
        this.itemsSelectedOrderList.setModel(itemsSelectedOrder);
        this.preparingOrdersList.setModel(activeOrders);
        this.readyOrdersList.setModel(readyOrders);
        this.fullPriceLabel.setText("R$ 0.00");
        for (Item item : this.restaurant.getMenuItems()) {
            if(item instanceof Snack) {
                this.snackSelector.addItem(item.getName());
            } else if(item instanceof Dish) {
                this.dishSelector.addItem(item.getName());
            } else if(item instanceof Drink) {
                this.drinkSelector.addItem(item.getName());
            } else if(item instanceof Dessert) {
                this.dessertSelector.addItem(item.getName());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        newOrderScreen = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        nameInput = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        snackSelector = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        snacksPriceLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        snacksIngredientsLabel = new javax.swing.JLabel();
        addSnackButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        dishSelector = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        dishesPriceLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dishesIngredientsLabel = new javax.swing.JLabel();
        addDishButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        dessertSelector = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        dessertsPriceLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        dessertsIngredientsLabel = new javax.swing.JLabel();
        addDessertButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        drinkSelector = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        drinksPriceLabel = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        drinksIngredientsLabel = new javax.swing.JLabel();
        addDrinkButton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        itensOrderList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        fullPriceLabel = new javax.swing.JLabel();
        removeItemButton = new javax.swing.JButton();
        finishOrderButton = new javax.swing.JButton();
        restaurantScreen = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        activeOrdersList = new javax.swing.JList<>();
        jPanel7 = new javax.swing.JPanel();
        concludeOrderButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        itemsSelectedOrderList = new javax.swing.JList<>();
        jLabel10 = new javax.swing.JLabel();
        selectedOrder = new javax.swing.JLabel();
        ordersScreen = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        readyOrdersList = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        preparingOrdersList = new javax.swing.JList<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setText("Nome:");

        nameInput.setMinimumSize(new java.awt.Dimension(150, 22));
        nameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameInputActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Lanches"));

        snackSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snackSelectorActionPerformed(evt);
            }
        });

        jLabel1.setText("Preço:");

        jLabel3.setText("Ingredientes:");

        snacksIngredientsLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        snacksIngredientsLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        addSnackButton.setText("Adicionar");
        addSnackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addSnackButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(snacksIngredientsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(snackSelector, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(snacksPriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addSnackButton)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(snackSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(snacksPriceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(snacksIngredientsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addSnackButton)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Pratos"));

        dishSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dishSelectorActionPerformed(evt);
            }
        });

        jLabel5.setText("Preço:");

        jLabel7.setText("Ingredientes:");

        dishesIngredientsLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        addDishButton.setText("Adicionar");
        addDishButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addDishButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dishSelector, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dishesPriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(dishesIngredientsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addDishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dishSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dishesPriceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dishesIngredientsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addDishButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Sobremesas"));

        dessertSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dessertSelectorActionPerformed(evt);
            }
        });

        jLabel9.setText("Preço:");

        jLabel11.setText("Ingredientes:");

        dessertsIngredientsLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        addDessertButton.setText("Adicionar");
        addDessertButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addDessertButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dessertSelector, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dessertsPriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addDessertButton))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(dessertsIngredientsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dessertSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(dessertsPriceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dessertsIngredientsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addDessertButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Bebidas"));

        drinkSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinkSelectorActionPerformed(evt);
            }
        });

        jLabel13.setText("Preço:");

        jLabel15.setText("Ingredientes:");

        drinksIngredientsLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        addDrinkButton.setText("Adicionar");
        addDrinkButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addDrinkButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(drinkSelector, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(drinksPriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addDrinkButton))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(drinksIngredientsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(drinkSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(drinksPriceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(drinksIngredientsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addDrinkButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Informações do pedido"));

        itensOrderList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(itensOrderList);

        jLabel2.setText("Valor total:");

        removeItemButton.setText("Remover Item");
        removeItemButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeItemButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fullPriceLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                        .addComponent(removeItemButton)
                        .addContainerGap())))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fullPriceLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 74, Short.MAX_VALUE)
                        .addComponent(removeItemButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        finishOrderButton.setText("Concluir Pedido");
        finishOrderButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                finishOrderButtonMouseClicked(evt);
            }
        });
        finishOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishOrderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newOrderScreenLayout = new javax.swing.GroupLayout(newOrderScreen);
        newOrderScreen.setLayout(newOrderScreenLayout);
        newOrderScreenLayout.setHorizontalGroup(
            newOrderScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newOrderScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newOrderScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newOrderScreenLayout.createSequentialGroup()
                        .addGap(0, 509, Short.MAX_VALUE)
                        .addComponent(finishOrderButton))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(newOrderScreenLayout.createSequentialGroup()
                        .addGroup(newOrderScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(newOrderScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(newOrderScreenLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        newOrderScreenLayout.setVerticalGroup(
            newOrderScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newOrderScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newOrderScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newOrderScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newOrderScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finishOrderButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Novo Pedido", newOrderScreen);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Restaurante: ");

        jLabel8.setText("Pedidos Ativos:");

        activeOrdersList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        activeOrdersList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                activeOrdersListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(activeOrdersList);

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        concludeOrderButton.setText("Concluir Pedido");
        concludeOrderButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                concludeOrderButtonMouseClicked(evt);
            }
        });

        itemsSelectedOrderList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane3.setViewportView(itemsSelectedOrderList);

        jLabel10.setText("Visualizar pedido :");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(concludeOrderButton))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectedOrder)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(selectedOrder))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(concludeOrderButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout restaurantScreenLayout = new javax.swing.GroupLayout(restaurantScreen);
        restaurantScreen.setLayout(restaurantScreenLayout);
        restaurantScreenLayout.setHorizontalGroup(
            restaurantScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(restaurantScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(restaurantScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(restaurantScreenLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(restaurantScreenLayout.createSequentialGroup()
                        .addGroup(restaurantScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(restaurantScreenLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(43, 43, 43)))
                        .addContainerGap())))
        );
        restaurantScreenLayout.setVerticalGroup(
            restaurantScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(restaurantScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(196, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Visão Estabelecimento", restaurantScreen);

        ordersScreen.setMinimumSize(new java.awt.Dimension(0, 0));

        jScrollPane4.setViewportView(readyOrdersList);

        jScrollPane5.setViewportView(preparingOrdersList);

        jLabel12.setText("Pedidos prontos");

        jLabel14.setText("Pedidos em preparo");

        javax.swing.GroupLayout ordersScreenLayout = new javax.swing.GroupLayout(ordersScreen);
        ordersScreen.setLayout(ordersScreenLayout);
        ordersScreenLayout.setHorizontalGroup(
            ordersScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ordersScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ordersScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
                .addGap(18, 46, Short.MAX_VALUE)
                .addGroup(ordersScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                    .addComponent(jLabel12))
                .addContainerGap())
        );
        ordersScreenLayout.setVerticalGroup(
            ordersScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ordersScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ordersScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ordersScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(jScrollPane5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ver pedidos", ordersScreen);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void finishOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishOrderButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finishOrderButtonActionPerformed

    private void finishOrderButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finishOrderButtonMouseClicked
        this.restaurant.generateUniqueOrder(this.client.getPedido());
        this.activeOrders.addElement(this.client.getPedido().getId() + "");
        this.client = new Client();
        this.orderItems.removeAllElements();
        this.fullPriceLabel.setText("R$ 0.00");
    }//GEN-LAST:event_finishOrderButtonMouseClicked

    private void removeItemButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeItemButtonMouseClicked
        String item = this.itensOrderList.getSelectedValue();
        if(item == null) {
            return;
        }
        Item itemFound = this.restaurant.getItemByName(item);
        Order pedido = this.client.getPedido();
        pedido.removeItem(itemFound);
        pedido.setFullPrice(pedido.getFullPrice() - itemFound.getPrice());
        this.fullPriceLabel.setText("R$ " + pedido.getFullPrice());
        this.orderItems.removeElementAt(this.itensOrderList.getSelectedIndex());
    }//GEN-LAST:event_removeItemButtonMouseClicked

    private void addDrinkButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDrinkButtonMouseClicked
        Object item = this.drinkSelector.getSelectedItem();
        Item itemFound = this.restaurant.getItemByName(item.toString());
        this.orderItems.addElement(item.toString());
        Order pedido = this.client.getPedido();
        pedido.addItem(itemFound);
        pedido.setFullPrice(pedido.getFullPrice() + itemFound.getPrice());
        this.fullPriceLabel.setText("R$ " + pedido.getFullPrice());
    }//GEN-LAST:event_addDrinkButtonMouseClicked

    private void drinkSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinkSelectorActionPerformed
        Object item = this.drinkSelector.getSelectedItem();
        Item itemFound = this.restaurant.getItemByName(item.toString());
        if(itemFound == null) {
            this.drinksIngredientsLabel.setText("Erro ao obter informações do item");
            this.drinksPriceLabel.setText("R$ 0,00");
            return;
        }
        this.drinksIngredientsLabel.setText(itemFound.getIngredients());
        this.drinksPriceLabel.setText("R$ " + itemFound.getPrice());
    }//GEN-LAST:event_drinkSelectorActionPerformed

    private void addDessertButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDessertButtonMouseClicked
        Object item = this.dessertSelector.getSelectedItem();
        Item itemFound = this.restaurant.getItemByName(item.toString());
        this.orderItems.addElement(item.toString());
        Order pedido = this.client.getPedido();
        pedido.addItem(itemFound);
        pedido.setFullPrice(pedido.getFullPrice() + itemFound.getPrice());
        this.fullPriceLabel.setText("R$ " + pedido.getFullPrice());
    }//GEN-LAST:event_addDessertButtonMouseClicked

    private void dessertSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dessertSelectorActionPerformed
        Object item = this.dessertSelector.getSelectedItem();
        Item itemFound = this.restaurant.getItemByName(item.toString());
        if(itemFound == null) {
            this.dessertsIngredientsLabel.setText("Erro ao obter informações do item");
            this.dessertsPriceLabel.setText("R$ 0,00");
            return;
        }
        this.dessertsIngredientsLabel.setText(itemFound.getIngredients());
        this.dessertsPriceLabel.setText("R$ " + itemFound.getPrice());
    }//GEN-LAST:event_dessertSelectorActionPerformed

    private void addDishButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDishButtonMouseClicked
        Object item = this.dishSelector.getSelectedItem();
        Item itemFound = this.restaurant.getItemByName(item.toString());
        this.orderItems.addElement(item.toString());
        Order pedido = this.client.getPedido();
        pedido.addItem(itemFound);
        pedido.setFullPrice(pedido.getFullPrice() + itemFound.getPrice());
        this.fullPriceLabel.setText("R$ " + pedido.getFullPrice());
    }//GEN-LAST:event_addDishButtonMouseClicked

    private void dishSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dishSelectorActionPerformed
        Object item = this.dishSelector.getSelectedItem();
        Item itemFound = this.restaurant.getItemByName(item.toString());
        if(itemFound == null) {
            this.dishesIngredientsLabel.setText("Erro ao obter informações do item");
            this.dishesPriceLabel.setText("R$ 0,00");
            return;
        }
        this.dishesIngredientsLabel.setText(itemFound.getIngredients());
        this.dishesPriceLabel.setText("R$ " + itemFound.getPrice());
    }//GEN-LAST:event_dishSelectorActionPerformed

    private void addSnackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addSnackButtonMouseClicked
        Object item = this.snackSelector.getSelectedItem();
        Item itemFound = this.restaurant.getItemByName(item.toString());
        this.orderItems.addElement(item.toString());
        Order pedido = this.client.getPedido();
        pedido.addItem(itemFound);
        pedido.setFullPrice(pedido.getFullPrice() + itemFound.getPrice());
        this.fullPriceLabel.setText("R$ " + pedido.getFullPrice());
    }//GEN-LAST:event_addSnackButtonMouseClicked

    private void snackSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snackSelectorActionPerformed
        Object item = this.snackSelector.getSelectedItem();
        Item itemFound = this.restaurant.getItemByName(item.toString());
        if(itemFound == null) {
            this.snacksIngredientsLabel.setText("Erro ao obter informações do item");
            this.snacksPriceLabel.setText("R$ 0,00");
            return;
        }
        this.snacksIngredientsLabel.setText(itemFound.getIngredients());
        this.snacksPriceLabel.setText("R$ " + itemFound.getPrice());
    }//GEN-LAST:event_snackSelectorActionPerformed

    private void nameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameInputActionPerformed
        this.client.setNome(this.nameInput.getText());
    }//GEN-LAST:event_nameInputActionPerformed

    private void activeOrdersListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_activeOrdersListValueChanged
        String selectedOrder = this.activeOrdersList.getSelectedValue();
        if(selectedOrder == null) {
            return;
        }
        this.itemsSelectedOrder.removeAllElements();
        Order pedido = this.restaurant.getOrderById(Integer.parseInt(this.activeOrdersList.getSelectedValue()));
        for(Item item : pedido.getItens()) {
            this.itemsSelectedOrder.addElement(item.getName());
        }
        this.selectedOrder.setText("" + pedido.getId());
    }//GEN-LAST:event_activeOrdersListValueChanged

    private void concludeOrderButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_concludeOrderButtonMouseClicked
        String selectedOrder = this.activeOrdersList.getSelectedValue();
        if(selectedOrder == null) {
            return;
        }
        this.itemsSelectedOrder.removeAllElements();
        Order pedido = this.restaurant.getOrderById(Integer.parseInt(this.activeOrdersList.getSelectedValue()));
        this.restaurant.updateOrderStatus(pedido, "Pronto");
        this.activeOrders.removeElementAt(this.activeOrdersList.getSelectedIndex());
        this.selectedOrder.setText("");
        this.readyOrders.addElement(selectedOrder);
    }//GEN-LAST:event_concludeOrderButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> activeOrdersList;
    private javax.swing.JButton addDessertButton;
    private javax.swing.JButton addDishButton;
    private javax.swing.JButton addDrinkButton;
    private javax.swing.JButton addSnackButton;
    private javax.swing.JButton concludeOrderButton;
    private javax.swing.JComboBox<String> dessertSelector;
    private javax.swing.JLabel dessertsIngredientsLabel;
    private javax.swing.JLabel dessertsPriceLabel;
    private javax.swing.JComboBox<String> dishSelector;
    private javax.swing.JLabel dishesIngredientsLabel;
    private javax.swing.JLabel dishesPriceLabel;
    private javax.swing.JComboBox<String> drinkSelector;
    private javax.swing.JLabel drinksIngredientsLabel;
    private javax.swing.JLabel drinksPriceLabel;
    private javax.swing.JButton finishOrderButton;
    private javax.swing.JLabel fullPriceLabel;
    private javax.swing.JList<String> itemsSelectedOrderList;
    private javax.swing.JList<String> itensOrderList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nameInput;
    private javax.swing.JPanel newOrderScreen;
    private javax.swing.JPanel ordersScreen;
    private javax.swing.JList<String> preparingOrdersList;
    private javax.swing.JList<String> readyOrdersList;
    private javax.swing.JButton removeItemButton;
    private javax.swing.JPanel restaurantScreen;
    private javax.swing.JLabel selectedOrder;
    private javax.swing.JComboBox<String> snackSelector;
    private javax.swing.JLabel snacksIngredientsLabel;
    private javax.swing.JLabel snacksPriceLabel;
    // End of variables declaration//GEN-END:variables
}
